"""
constants.py — Shared constants layer to prevent drift
"""

NO_RETRY_TYPES = {"FRAUD_FLAGGED", "CARD_BLOCKED", "HIGH_RISK_DEFAULT"}
MAX_RETRY_ATTEMPTS = 3
MAX_OUTREACH_ATTEMPTS = 3
COOLDOWN_MINUTES = 30
MIN_RECOVERABLE_AMOUNT_PAISE = 1000  # ₹10
